neighbour_connexion:
    path:     /
    defaults: { _controller: NeighbourBundle:Home:index }

neighbour_homepage:
    path:     /home/{userHash}
    defaults: { _controller: NeighbourBundle:Home:home }
