<?php

namespace NeighbourBundle\Repository;

/**
 * ToollistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToollistRepository extends \Doctrine\ORM\EntityRepository
{
}
